export const ADD_TODO = "ADD_TODO";
export const FETCH_TODOS_LOADING = "FETCH_TODOS_LOADING";
export const FETCH_TODOS_ERROR = "FETCH_TODOS_ERROR";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
