export const ADD_TODO = "ADD_TODO";
export const FETCH_TODOS_START = "FETCH_TODOS_START";
export const FETCH_TODOS_ERROR = "FETCH_TODOS_ERROR";
export const FETCH_TODOS_SUCCESS = "FETCH_TODOS_SUCCESS";
export const TODOS_FILTERED = "TODOS_FILTERED";
